//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toko_buku
{
    using System;
    using System.Collections.Generic;
    
    public partial class kasir
    {
        public int id_kasir { get; set; }
        public string nama { get; set; }
        public string alamat { get; set; }
        public string telepon { get; set; }
        public string status { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string akses { get; set; }
        public byte[] image { get; set; }
    }
}
